<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SUFIYAN" failures="1" tests="3" name="Test" time="3.325" errors="0" timestamp="2023-04-04T14:56:18 IST">
  <testcase classname="com.Test.TC_Login" name="login_Test" time="3.259"/>
  <testcase classname="com.Test.apptest" name="testlogin1" time="0.012"/>
  <testcase classname="com.Test.apptest" name="testlogin2" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at com.Test.apptest.testlogin2(apptest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testlogin2 -->
</testsuite> <!-- Test -->
